
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  desc = _buf["desc"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  prefab = _buf["prefab"]; }
        { if(!_buf["script"].IsString) { throw new SerializationException(); }  script = _buf["script"]; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  moveSpeed = _buf["moveSpeed"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new Bullet(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly string id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string desc;
    public readonly string prefab;
    public readonly string script;
    public readonly float moveSpeed;
   
    public const int __ID__ = 2000900386;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "prefab:" + prefab + ","
        + "script:" + script + ","
        + "moveSpeed:" + moveSpeed + ","
        + "}";
    }
}

}
