
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Character : Luban.BeanBase
{
    public Character(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  desc = _buf["desc"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  prefab = _buf["prefab"]; }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } skills = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  skills.Add(__v0); }   }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  moveSpeed = _buf["moveSpeed"]; }
    }

    public static Character DeserializeCharacter(JSONNode _buf)
    {
        return new Character(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly string id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string desc;
    public readonly string prefab;
    public readonly System.Collections.Generic.List<string> skills;
    public readonly float moveSpeed;
   
    public const int __ID__ = -726803703;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "prefab:" + prefab + ","
        + "skills:" + Luban.StringUtil.CollectionToString(skills) + ","
        + "moveSpeed:" + moveSpeed + ","
        + "}";
    }
}

}
