
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    public enum CookbookType
    {
        软饮 = 1,
        基酒 = 2,
        餐点 = 3,
        甜品 = 4,
    }

} 

