
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  desc = _buf["desc"]; }
        { if(!_buf["script"].IsString) { throw new SerializationException(); }  script = _buf["script"]; }
        { if(!_buf["bullet"].IsString) { throw new SerializationException(); }  bullet = _buf["bullet"]; }
    }

    public static Skill DeserializeSkill(JSONNode _buf)
    {
        return new Skill(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly string id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string desc;
    public readonly string script;
    public readonly string bullet;
   
    public const int __ID__ = 79944241;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "desc:" + desc + ","
        + "script:" + script + ","
        + "bullet:" + bullet + ","
        + "}";
    }
}

}
