
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public unit.TbCharacter TbCharacter {get; }
    public skill.TbSkill TbSkill {get; }
    public skill.TbBullet TbBullet {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCharacter = new unit.TbCharacter(loader("unit_tbcharacter"));
        TbSkill = new skill.TbSkill(loader("skill_tbskill"));
        TbBullet = new skill.TbBullet(loader("skill_tbbullet"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacter.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbBullet.ResolveRef(this);
    }
}

}
