
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.unit
{
public partial class TbCharacter
{
    private readonly System.Collections.Generic.Dictionary<string, Character> _dataMap;
    private readonly System.Collections.Generic.List<Character> _dataList;
    
    public TbCharacter(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Character>();
        _dataList = new System.Collections.Generic.List<Character>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Character _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Character.DeserializeCharacter(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Character> DataMap => _dataMap;
    public System.Collections.Generic.List<Character> DataList => _dataList;

    public Character GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Character Get(string key) => _dataMap[key];
    public Character this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
